categories: 
  - Sequence Analysis
description: Predicts the presence and location of signal peptide cleavage sites in amino acid sequences from different organisms
homepage_url: http://www.predisi.de/home.html
name: predisi
owner: jpmen
remote_repository_url: https://github.com/jpmeneboo/galaxytool/tree/master/tool/predisi/
